### ISSUE TITLE
[Bug] Graphical issues in Burning Rangers

### ISSUE THREAD

**Issue by GoodWall533** [StrikerX3/Ymir#130]
Burning Rangers in Ymir suffers from some graphical problems:

![Image](https://github.com/user-attachments/assets/43adb6b9-a565-4c01-ad5b-310eb8587963)

![Image](https://github.com/user-attachments/assets/f09d432e-c753-4a43-ba60-0ef343547c24)
The background and the character models of the protags in the character select don't render correctly.

![Image](https://github.com/user-attachments/assets/ae09f56b-2d11-4658-90a0-ad244d0f2092)
The tutorial also has issues, the level doesn't render at all.

**Comment by secreto** [comment]
I tested with the build with the latest changes and for me it looks like this:

![Image](https://github.com/user-attachments/assets/0a24f01d-c156-4591-b1fb-397a7c03152a)

![Image](https://github.com/user-attachments/assets/912cc88b-9947-4daa-8ed9-09c6fc9bb564)

![Image](https://github.com/user-attachments/assets/e8176364-f0ab-4d3f-bdcc-4a4cbaad1465)

![Image](https://github.com/user-attachments/assets/6bcca1f4-2a62-4de1-8d91-4084ea27b012)

**Comment by secreto** [comment]
I tested again with the dev build and it seems that disabling the Threaded VDP Renderer fixes most issues.

**Comment by GoodWall533** [comment]
The graphical issues seems to have been fixed in the lastest dev build available (29/05/2025) in the Discord:

![Image](https://github.com/user-attachments/assets/ea8a58c5-2bf1-434f-a3f9-6acb41d4bd13)

![Image](https://github.com/user-attachments/assets/8a5b9fc6-81ad-4c58-9f53-4861daecaa92)

These screenshots were taken with the Threaded VDP 1/2 turned on.

**Comment by AydanWatkins** [comment]
![Image](https://github.com/user-attachments/assets/55bd0d32-2de5-4eca-ac54-26459622e1d2)

FIXED as of dev build 0.1.4 (30/05/20205). I think this can be closed now, the audio issue can remain open however as that still exists.

**Comment by secreto** [comment]
I kept testing with the latest dev builds and the glitches sometimes trigger and sometimes not with Threaded VDP.

**Comment by secreto** [comment]
I found how to reliably reproduce the glitches with Threaded VDP ON in the 2025-05-31 dev build.

When starting Ymir if I load the game disc before reaching the BIOS System screen, then when the first mission begins the glitches happen. 
If I soft reset the game and try again the glitches do not occur.
When I fresh start Ymir and let the Saturn system properly load and then I load the game then the in-game glitches don't occur.

**Comment by AydanWatkins** [comment]
I wonder if this is linked to that infamous CROC glitch that happened on Saturn in Europe where you had to boot to the bios BEFORE you put the game disc in because the game code didn't load some kind of call to VDP which made the game graphics be all glitched out... When you enter BIOS the VDP rendering calls are all made for the cubes and the GUI, starship, stars etc. so launching the game then means that it would look and load normally.

**Comment by AydanWatkins** [comment]
I can confirm too that @secreto method produces the bug every time, if you load the rom super fast so that it never gets to the bios screen but just loads into the game, it does produce the graphical glitches.

![Image](https://github.com/user-attachments/assets/f4b3a382-599c-4aff-ac01-9cc3aa418e7f)

**Comment by GoodWall533** [comment]
The game seems to have a regression, the graphics broke again while having the threaded vdp option turned on. Everything is fine with it turned off.

**Comment by GoodWall533** [comment]
Burning Rangers graphics work fine on the latest dev build available, screenshot by Aydan Watkins:

![Image](https://github.com/user-attachments/assets/a89eab9a-7685-44f8-8eb0-54fc86230f9c)

And they have been working fine for a while now so i guess its safe to close this.
