### ISSUE TITLE
NFL Quarterback Club 97 (USA) - Graphical garbage on title screen

### ISSUE THREAD

**Issue by thelastangryman1907** [StrikerX3/Ymir#332]
When you start a new game and go to the main menu there's a bit of graphical garbage on screen for a few seconds.

<img width="1918" height="1010" alt="Image" src="https://github.com/user-attachments/assets/9856ea26-076f-45d1-b099-93f0411ad6b6" />

**Comment by StrikerX3** [comment]
Fixed in 62d131bc33a7afe649529b4d7b971e5c8f6291a4

**Comment by thelastangryman1907** [comment]
Title screen is now fixed but when you pause during gameplay there's a few frames of graphical garbage. 

<img width="1918" height="1008" alt="Image" src="https://github.com/user-attachments/assets/7cd46c97-f1b6-46ae-8ec7-7bbdb5775ba8" />

**Comment by StrikerX3** [comment]
First fix included in [0.1.7](https://github.com/StrikerX3/Ymir/releases/tag/v0.1.7).

**Comment by thelastangryman1907** [comment]
Fixed.

**Comment by thelastangryman1907** [comment]
@StrikerX3 

This regressed at some point. 

<img width="1280" height="960" alt="Image" src="https://github.com/user-attachments/assets/d4a7820e-3e74-43af-9e5a-a40e31f9deb5" />

**Comment by StrikerX3** [comment]
~~Fixed again in 41e633d563691102019e0e960266ae788f35fa10~~ Commit reverted until a proper solution is found

This was broken by the hack introduced to fix #438 and #446, which is now removed and replaced with computing VRAM access at the start of the frame instead of every scanline.

The lack of in-depth info on VRAM access patterns, and the fact that a lot of games set them up incorrectly, makes this a wild goose chase.

**Comment by StrikerX3** [comment]
Not quite fixed yet. The FMV now flickers.

See... wild goose chase.

**Comment by StrikerX3** [comment]
The correct fix for this particular issue is to remove the bitmap access on SH2 hack. No FMV flickers, no garbage on title screen. But that alone breaks Lunar - Silver Story and Shin Kaitei Gunkan. In order to fix those two I need to find a way to slow down SCU DMA transfers or stall the CPU, but don't stall for too long because some games hate it when things are too slow (or too fast).

Changing [this number](https://github.com/StrikerX3/Ymir/blob/7f98b32bc76180973426483da513254d9415b872/libs/ymir-core/src/ymir/hw/scu/scu.cpp#L1063) to a lucky 777 slows SCU DMA interrupts long enough to move the flickering line out of the way for both games, but as noted in the comments, this causes problems with other games.

**Comment by thelastangryman1907** [comment]
Fixed again.
